@startuml
'https://plantuml.com/class-diagram

interface Doclet {
    + init(locale : Locale, reporter : Reporter)
    + getName() : String
    + SourceVersion getSupportedSourceVersion()
    + run(environment : DocletEnvironment) : Boolean
}

class Locale {
}

interface DocletEnvironment {
}

interface Reporter {
}

enum SourceVersion {
}

Doclet --> Locale : "Use">
Doclet --> DocletEnvironment : "Use">
Doclet --> Reporter : "Use">
Doclet --> SourceVersion : "Use">

@enduml
